# Generated by Django 4.1.3 on 2022-11-02 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstREST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
